# Form implementation generated from reading ui file 'battery.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(520, 394)

            self.centralwidget = QtWidgets.QWidget(parent=MainWindow)

            # ========= FRAME VOLTAGE =========
            self.frameVoltage = QtWidgets.QFrame(self.centralwidget)
            self.frameVoltage.setGeometry(QtCore.QRect(60, 50, 160, 100))
            self.frameVoltage.setFrameShape(QtWidgets.QFrame.Shape.Box)
            self.frameVoltage.setLineWidth(2)

            self.labelVoltage = QtWidgets.QLabel("Voltage (V)", self.frameVoltage)
            self.labelVoltage.setGeometry(20, 10, 120, 20)

            self.voltage = QtWidgets.QLabel("0.00", self.frameVoltage)
            self.voltage.setGeometry(30, 40, 100, 40)
            self.voltage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.voltage.setStyleSheet("font-size: 24px; font-weight: bold;")

            # ========= FRAME CURRENT =========
            self.frameCurrent = QtWidgets.QFrame(self.centralwidget)
            self.frameCurrent.setGeometry(QtCore.QRect(300, 50, 160, 100))
            self.frameCurrent.setFrameShape(QtWidgets.QFrame.Shape.Box)
            self.frameCurrent.setLineWidth(2)

            self.labelCurrent = QtWidgets.QLabel("Current (A)", self.frameCurrent)
            self.labelCurrent.setGeometry(20, 10, 120, 20)

            self.ampe = QtWidgets.QLabel("0.00", self.frameCurrent)
            self.ampe.setGeometry(30, 40, 100, 40)
            self.ampe.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.ampe.setStyleSheet("font-size: 24px; font-weight: bold;")

            # ========= FRAME POWER =========
            self.framePower = QtWidgets.QFrame(self.centralwidget)
            self.framePower.setGeometry(QtCore.QRect(60, 180, 160, 100))
            self.framePower.setFrameShape(QtWidgets.QFrame.Shape.Box)
            self.framePower.setLineWidth(2)

            self.labelPower = QtWidgets.QLabel("Power (W)", self.framePower)
            self.labelPower.setGeometry(30, 10, 100, 20)

            self.power = QtWidgets.QLabel("0.0", self.framePower)
            self.power.setGeometry(30, 40, 100, 40)
            self.power.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.power.setStyleSheet("font-size: 24px; font-weight: bold;")

            # ========= FRAME ENERGY =========
            self.frameEnergy = QtWidgets.QFrame(self.centralwidget)
            self.frameEnergy.setGeometry(QtCore.QRect(300, 180, 160, 100))
            self.frameEnergy.setFrameShape(QtWidgets.QFrame.Shape.Box)
            self.frameEnergy.setLineWidth(2)

            self.labelEnergy = QtWidgets.QLabel("Energy (kWh)", self.frameEnergy)
            self.labelEnergy.setGeometry(20, 10, 120, 20)

            self.energy = QtWidgets.QLabel("0.000", self.frameEnergy)
            self.energy.setGeometry(30, 40, 100, 40)
            self.energy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.energy.setStyleSheet("font-size: 22px; font-weight: bold;")

            # ========= RESET BUTTON =========
            self.btnReset = QtWidgets.QPushButton("RESET", self.centralwidget)
            self.btnReset.setGeometry(QtCore.QRect(220, 300, 80, 30))

            MainWindow.setCentralWidget(self.centralwidget)

            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            MainWindow.setStatusBar(self.statusbar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelVoltage.setText(_translate("MainWindow", "Voltage (V)"))
        self.labelCurrent.setText(_translate("MainWindow", "Current (A)"))
        self.labelPower.setText(_translate("MainWindow", "Power (W)"))
        self.labelEnergy.setText(_translate("MainWindow", "Energy (kWh)"))
        self.btnReset.setText(_translate("MainWindow", "RESET"))
        self.voltage.setText(_translate("MainWindow", ""))
        self.ampe.setText(_translate("MainWindow", ""))
        self.power.setText(_translate("MainWindow", ""))
        self.energy.setText(_translate("MainWindow", ""))
